CREATE TABLE IF NOT EXISTS transactions(
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL ,
amount DECIMAL(10,2) NOT NULL,
description VARCHAR(255) NOT NULL,
date DATE NOT NULL DEFAULT CURRENT_DATE,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
PRIMARY KEY(id),
FOREIGN KEY (user_id) REFERENCES users (id)
)